config/routes.rb
Rails.application.routes.draw do
  root 'ajaxcallprocess#home'

  get 'about' =>'ajaxcallprocess#about'
  get 'contact'=> 'ajaxcallprocess#contact'

end

app/models/eventinfo.rb
class Eventinfo < ActiveRecord::Base
end

app/controllers/ajaxcallprocess_controller.rb
class AjaxcallprocessController < ApplicationController
  def home

    @data=Eventinfo.all
    respond_to do |t|
      t.html
      t.json {render json: @data}
    end
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.description
      marker.picture({
                         "url"=> "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                         "width" => 32,
                         "height" =>32
                     })
      marker.json({title: user.title})

    end
  end

  def about
  end

  def contact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ajaxcallprocess_helper.rb
module AjaxcallprocessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ajaxcallprocess/about.html.erb
<% provide(:variable,"About") %>

<h1> This Page will be update during the upcoming Home works</h1>

app/views/ajaxcallprocess/contact.html.erb
<% provide(:variable,"Contact") %>

<h1>This page will be updated during upcoming Home Works</h1>

app/views/ajaxcallprocess/home.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<% provide(:variable,"Home") %>

<div class="center jumbotron">

  <h2> Hackathons for the year 2015</h2>

  <button  class="btn btn-lg btn-success" id="button-click"> click Here</button>

</div>
<div class="mapie" id="mapping" style='width: 250px;float:right;'>
  <div  id="multi_markers" style='width: 250px; height: 250px;'></div>
</div>


<table class="parent" id="table" border="1" style="width:50%" value="a"></table>

<div class="graphing">
<svg id="graph" width="400" height="400"></svg>
</div>

app/views/layouts/_footer.erb
<footer class="footer">

  <small id="name">
    ashwin.raju93@mavs.uta.edu 1001213547
  </small>

</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>

      <%=link_to("My App","#",id:"logo") %>
    </div>
    <nav class="navbar-inner">

      <div class="collapse navbar-collapse" id="main">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("About",about_path) %></li>
          <li><%=  link_to("contact",contact_path)%></li>
        </ul>


      </div>
    </nav>
  </div>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:variable)%> Ruby on Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>

<%= render 'layouts/footer' %>
</html>